// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtK6Hyz-OWB850IC0P1U4VicmspbTPPig',
    appId: '1:984319075366:web:df2f66a8ea69bb1212f2e7',
    messagingSenderId: '984319075366',
    projectId: 'controledespesas-85d96',
    authDomain: 'controledespesas-85d96.firebaseapp.com',
    storageBucket: 'controledespesas-85d96.firebasestorage.app',
    measurementId: 'G-6B38SS1H9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SJYmuPGHGWdoG5AwlmXF7YIU5g9CTjI',
    appId: '1:984319075366:android:900ee42aef96d8d312f2e7',
    messagingSenderId: '984319075366',
    projectId: 'controledespesas-85d96',
    storageBucket: 'controledespesas-85d96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCca240OrlK_Zn_TV32K02KcLBkVJegSwY',
    appId: '1:984319075366:ios:53d170d1259ebbcc12f2e7',
    messagingSenderId: '984319075366',
    projectId: 'controledespesas-85d96',
    storageBucket: 'controledespesas-85d96.firebasestorage.app',
    iosBundleId: 'com.example.controleDespesas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCca240OrlK_Zn_TV32K02KcLBkVJegSwY',
    appId: '1:984319075366:ios:53d170d1259ebbcc12f2e7',
    messagingSenderId: '984319075366',
    projectId: 'controledespesas-85d96',
    storageBucket: 'controledespesas-85d96.firebasestorage.app',
    iosBundleId: 'com.example.controleDespesas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtK6Hyz-OWB850IC0P1U4VicmspbTPPig',
    appId: '1:984319075366:web:d56eb215eb9e32da12f2e7',
    messagingSenderId: '984319075366',
    projectId: 'controledespesas-85d96',
    authDomain: 'controledespesas-85d96.firebaseapp.com',
    storageBucket: 'controledespesas-85d96.firebasestorage.app',
    measurementId: 'G-41ZYNV9SMP',
  );
}
